Support for typing.Literal as an alternative to Enum in Python 3.8+.
fastapi/typer pull request #429
Opened 2022-07-14 16:47 UTC by blackary

Copied PR #174 from someone who deleted their account because I think it's worth reopening this PR and adding this functionality to typer.

Original PR message:
> Support for typing.Literal for creating choices, without actually having to create Enum types. Requires Python 3.8, referenced in https://github.com/tiangolo/typer/issues/76. I ran tests again 3.6 without problems, so I think the version check if working OK.

2022-12-21 20:27 UTC, markcheeky commented
Any update on merging this?

2023-01-01 14:19 UTC, markcheeky commented
Any updates on merging this? @tiangolo

2023-02-04 16:22 UTC, hoishing commented
Upvote for this PR, as using Literal is more succinct then using enum.

2023-02-16 13:33 UTC, atmartinez reviewed
There is the possibility to import Literal from typing_extensions to allow this to work for 3.6 (since Typer still says it support it [despite being EOL](https://devguide.python.org/versions/#unsupported-versions)) and 3.7 as well. This may be a moot consideration soon though since 3.7 [goes EOL in June 2023](https://devguide.python.org/versions/#supported-versions) as well if there are any plans to drop unsupported Python versions at some point. 

This may require adding a specific dependency for typing_extensions, but it's currently being installed by another dep regardless from some of the CI runs I checked for 3.6+ 4.1-4.4 depending on the Python version. 

[Example implementation for using typing_extensions](https://github.com/CompVis/taming-transformers/pull/114/files)

2023-07-13 07:56 UTC, Yarden-zamir approved these changes

2024-06-03 14:20 UTC, svlandeg commented
Preview of new docs section: https://a0405a66.typertiangolo.pages.dev/tutorial/parameter-types/enum/#literal-choices

2024-06-03 14:23 UTC, svlandeg commented
Thanks for this PR @blackary! I've taken the liberty to update this PR with the latest from `master`. I also added some improvements using new functionality from `_typing.py`, taking inspiration from the similar PR #669. This PR and that one now both cover largely the same functionality. I would personally merge this one and close the other, but will leave the final decision with Tiangolo as usual 😇

2024-06-03 14:25 UTC, blackary commented
Thanks @svlandeg!

2024-07-04 10:17 UTC, k4black commented
Gently ping @tiangolo

2024-08-08 06:38 UTC, Tremeschin commented
I have a really interesting use case for this PR, basically to copy a pydantic class signature's to a wrapper method to be [used directly as a typer command](https://github.com/BrokenSource/BrokenSource/blob/76de3f0c2716aa9bf538028c5bd0df3af77e321e/Broken/Core/__init__.py#L167), to avoid defining Enums for every [models' fields](https://github.com/BrokenSource/BrokenSource/blob/76de3f0c2716aa9bf538028c5bd0df3af77e321e/Broken/Externals/Depthmap.py#L129) where a Literal is shorter!

Softly pinging @tiangolo again 😄

2024-08-09 08:36 UTC, svlandeg commented
Hi all,

There's no need for pinging individual maintainers - this PR is on our internal board and will be reviewed further when Tiangolo has time. All the additional pings make our Github notifications difficult to use and only costs more time 😉 Thanks for your patience!

2024-08-09 08:56 UTC, k4black commented
Hey Sofie,

Thank you for reaching out! It's great to see the team growing, and I hope this will help the project develop and thrive. As well the old yet important PR are checked.

As a community, we would really appreciate feedback from the maintainers (e.g., "won't fix," "in process," etc.) to better understand the status of the PRs and avoid unnecessary pings. The only reason for pinging is the complete absence of information.

Thank you again for the updates!

2024-09-02 14:25 UTC, svlandeg commented
Currently, the CI is failing with 
```
Run ls -la coverage
ls: cannot access 'coverage': No such file or directory
Error: Process completed with exit code 2.
```

I'm pretty confused why this happens here though 🤔

2024-11-03 07:18 UTC, sshwy commented
Sorry to bother. I wonder what's the status of this PR?

2024-11-21 11:57 UTC, guilhermedelyra commented
is this close to being merged?

2024-11-21 12:44 UTC, oyarsa commented
For those waiting on this, there is a workaround until this gets merged: use `typer.Option(click_type=click.Choice(values))`. It's very verbose, but it works properly.

```py
from typing import Annotated

import click
import typer


def main(
    animal: Annotated[
        str, typer.Option(click_type=click.Choice(["dog", "cat", "ferret"]))
    ] = "dog",
) -> None:
    print(animal)


if __name__ == "__main__":
    typer.run(main)
```

Result:
```console
$ python t.py 
dog

$ python t.py --animal turtle
Usage: t.py [OPTIONS]
Try 't.py --help' for help.
╭─ Error ────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Invalid value for '--animal': 'turtle' is not one of 'dog', 'cat', 'ferret'.                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────╯

$ python t.py --help
                                                                                                          
 Usage: t.py [OPTIONS]                                                                                    
                                                                                                          
╭─ Options ──────────────────────────────────────────────────────────────────────────────────────────────╮
│ --animal        [dog|cat|ferret]  [default: dog]                                                       │
│ --help                            Show this message and exit.                                          │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────╯


$ python t.py 
dog

$ python t.py --animal ferret
ferret

$ python t.py --animal turtle
Usage: t.py [OPTIONS]
Try 't.py --help' for help.
╭─ Error ────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Invalid value for '--animal': 'turtle' is not one of 'dog', 'cat', 'ferret'.                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

2025-03-02 17:05 UTC, Kludex requested changes
This should work for `typing_extensions.Literal` on 3.7 as well.

I don't think the `needs_py38` is needed.

2025-03-02 17:31 UTC, Kludex commented on typer/_typing.py
> +    return get_origin(type_) in (Literal, typing_extensions.Literal)
A `typing_extensions.Literal` should also work with higher Python versions.

2025-03-02 17:36 UTC, Kludex approved these changes

2025-04-01 06:25 UTC, KonradStanski commented
If we could please merge this that would super appreciated!

2025-04-05 16:50 UTC, dandavison commented
@oyarsa thanks! It looks like this extension of your idea works to avoid manually duplicating the set of values in the `Literal`:

```python
    typing.Annotated[
        str, typer.Option(click_type=click.Choice(typing.get_args(MyLiteral)))
    ],
```

2025-05-14 21:26 UTC, xandaaah commented
Will this be merged? It's been almost 3 years now.

2025-06-09 12:07 UTC, estyrke commented
> @oyarsa thanks! It looks like this extension of your idea works to avoid manually duplicating the set of values in the `Literal`:
> 
> ```python
>     typing.Annotated[
>         str, typer.Option(click_type=click.Choice(typing.get_args(MyLiteral)))
>     ],
> ```

You could also annotate it as the literal instead of str:

```python
    typing.Annotated[
        MyLiteral, typer.Option(click_type=click.Choice(typing.get_args(MyLiteral)))
    ],
```

2025-08-27 14:19 UTC, svlandeg commented
Update:

- Removed the `needs_py38` as per Kludex's comment
- Updated the tests that started failing due to other changes on the `master` branch after the CI ran last time on this PR. All green again.

2025-09-18 17:57 UTC, pdjohntony commented
I was really hoping this got merged for the latest release 2 weeks ago 👀

2025-09-20 07:51 UTC, merged